# Generated by Django 6.0.2 on 2026-02-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion2Peos',
            fields=[
                ('criterion2_id', models.AutoField(primary_key=True, serialize=False)),
                ('institutional_mission_statement', models.TextField()),
                ('program_mission_statement', models.TextField()),
                ('mission_source_link', models.TextField()),
                ('peos_list', models.TextField()),
                ('peos_short_descriptions', models.TextField()),
                ('peos_publication_location', models.TextField()),
                ('peos_mission_alignment_explanation', models.TextField()),
                ('constituencies_list', models.TextField()),
                ('constituencies_contribution_description', models.TextField()),
                ('peo_review_frequency', models.TextField()),
                ('peo_review_participants', models.TextField()),
                ('feedback_collection_and_decision_process', models.TextField()),
                ('changes_since_last_peo_review', models.TextField()),
            ],
            options={
                'db_table': 'CRITERION_2_PEOS',
            },
        ),
        migrations.CreateModel(
            name='Criterion3SoPeo',
            fields=[
                ('criterion3_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CRITERION_3_SO_PEO',
            },
        ),
        migrations.CreateModel(
            name='CycleChecklist',
            fields=[
                ('checklist_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'CYCLE_CHECKLIST',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255, unique=True)),
                ('program_level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PROGRAM',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ROLE',
            },
        ),
        migrations.CreateModel(
            name='AccreditationCycle',
            fields=[
                ('cycle_id', models.AutoField(db_column='Cycle_ID', primary_key=True, serialize=False)),
                ('start_year', models.IntegerField(db_column='Start_year')),
                ('end_year', models.IntegerField(db_column='End_year')),
                ('overall_progress_percentage', models.DecimalField(db_column='Overall_Progress_Percentage', decimal_places=2, max_digits=5)),
                ('criterion2', models.ForeignKey(db_column='criterion2_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion2peos')),
                ('criterion3', models.ForeignKey(db_column='criterion3_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion3sopeo')),
                ('checklist', models.ForeignKey(db_column='checklist_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.cyclechecklist')),
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.program')),
            ],
            options={
                'db_table': 'ACCREDIATION_CYCLE',
            },
        ),
        migrations.CreateModel(
            name='Criterion7Facilities',
            fields=[
                ('criterion7_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_number_of_offices', models.IntegerField(blank=True, null=True)),
                ('average_workspace_size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('guidance_description', models.TextField(blank=True, null=True)),
                ('responsible_faculty_name', models.CharField(blank=True, max_length=255, null=True)),
                ('maintenance_policy_description', models.TextField(blank=True, null=True)),
                ('technical_collections_and_journals', models.TextField(blank=True, null=True)),
                ('electronic_databases_and_eresources', models.TextField(blank=True, null=True)),
                ('faculty_book_request_process', models.TextField(blank=True, null=True)),
                ('library_access_hours_and_systems', models.TextField(blank=True, null=True)),
                ('facilities_support_student_outcomes', models.TextField(blank=True, null=True)),
                ('safety_and_inspection_processes', models.TextField(blank=True, null=True)),
                ('compliance_with_university_policy', models.TextField(blank=True, null=True)),
                ('student_availability_details', models.TextField(blank=True, null=True)),
                ('cycle', models.ForeignKey(db_column='Cycle_ID', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.accreditationcycle')),
            ],
            options={
                'db_table': 'CRITERION_7_FACILITIES',
            },
        ),
        migrations.CreateModel(
            name='ComputingResources',
            fields=[
                ('computing_resources_id', models.AutoField(primary_key=True, serialize=False)),
                ('computing_resource_name', models.CharField(max_length=255)),
                ('computing_resource_location', models.TextField()),
                ('computing_adequacy_notes', models.TextField()),
                ('computing_hours_available', models.TextField()),
                ('computing_access_type', models.TextField()),
                ('criterion7', models.ForeignKey(db_column='criterion7_id', on_delete=django.db.models.deletion.CASCADE, related_name='computing_resources', to='abet_criteria.criterion7facilities')),
            ],
            options={
                'db_table': 'COMPUTING_RESOURCES',
            },
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_room', models.CharField(max_length=50)),
                ('classroom_capacity', models.IntegerField()),
                ('classroom_multimedia', models.TextField()),
                ('classroom_internet_access', models.TextField()),
                ('classroom_typical_use', models.TextField()),
                ('classroom_adequacy_comments', models.TextField()),
                ('criterion7', models.ForeignKey(db_column='criterion7_id', on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='abet_criteria.criterion7facilities')),
            ],
            options={
                'db_table': 'CLASSROOMS',
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('completion_percentage', models.DecimalField(db_column='completion_percetage', decimal_places=2, max_digits=5)),
                ('criterion3', models.ForeignKey(blank=True, db_column='criterion3_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion3sopeo')),
                ('criterion7', models.ForeignKey(blank=True, db_column='criterion7_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion7facilities')),
                ('checklist', models.ForeignKey(db_column='checklist_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.cyclechecklist')),
            ],
            options={
                'db_table': 'CHECKLIST_ITEM',
            },
        ),
        migrations.CreateModel(
            name='Criterion8InstitutionalSupport',
            fields=[
                ('criterion8_id', models.AutoField(primary_key=True, serialize=False)),
                ('leadership_structure_description', models.TextField()),
                ('leadership_adequacy_description', models.TextField()),
                ('leadership_participation_description', models.TextField()),
                ('budget_process_continuity', models.TextField()),
                ('teaching_support_description', models.TextField()),
                ('infrastructure_funding_description', models.TextField()),
                ('resource_adequacy_description', models.TextField()),
                ('hiring_process_description', models.TextField()),
                ('retention_strategies_description', models.TextField()),
                ('professional_development_support_types', models.TextField()),
                ('professional_development_request_process', models.TextField()),
                ('professional_development_funding_details', models.TextField()),
                ('additional_narrative_on_staffing', models.TextField(db_column='Additional_narrative_on_staffing')),
                ('cycle', models.ForeignKey(db_column='Cycle_ID', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.accreditationcycle')),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.checklistitem')),
            ],
            options={
                'db_table': 'CRITERION_8_INSTITUTIONAL_SUPPORT',
            },
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=255)),
                ('lab_room', models.CharField(max_length=50)),
                ('lab_category', models.CharField(max_length=100)),
                ('lab_hardware_list', models.TextField()),
                ('lab_software_list', models.TextField()),
                ('lab_open_hours', models.TextField()),
                ('lab_courses_using_lab', models.TextField()),
                ('criterion7', models.ForeignKey(db_column='criterion7_id', on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='abet_criteria.criterion7facilities')),
            ],
            options={
                'db_table': 'LABORATORIES',
            },
        ),
        migrations.CreateModel(
            name='StaffingRow',
            fields=[
                ('staffing_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('number_of_staff', models.IntegerField()),
                ('primary_role', models.CharField(max_length=255)),
                ('training_retention_practices', models.TextField()),
                ('criterion8', models.ForeignKey(db_column='criterion8_id', on_delete=django.db.models.deletion.CASCADE, related_name='staffing_rows', to='abet_criteria.criterion8institutionalsupport')),
            ],
            options={
                'db_table': 'STAFFING_ROW',
            },
        ),
        migrations.CreateModel(
            name='UpgradingFacilities',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=255)),
                ('next_scheduled_upgrade', models.DateField()),
                ('last_upgrade_date', models.DateField()),
                ('maintenance_notes', models.TextField()),
                ('responsible_staff', models.CharField(max_length=255)),
                ('criterion7', models.ForeignKey(db_column='criterion7_id', on_delete=django.db.models.deletion.CASCADE, related_name='upgrading_facilities', to='abet_criteria.criterion7facilities')),
            ],
            options={
                'db_table': 'UPGRADING_FACILITES',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.role')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('evidence_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('upload_date', models.DateField()),
                ('cycle', models.ForeignKey(db_column='Cycle_ID', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.accreditationcycle')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.user')),
            ],
            options={
                'db_table': 'EVIDENCE_FILE',
            },
        ),
    ]
