# Generated by Django 6.0.2 on 2026-02-10 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet_criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion7facilities',
            name='cycle',
            field=models.ForeignKey(blank=True, db_column='Cycle_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.accreditationcycle'),
        ),
    ]
