# Generated by Django 6.0.2 on 2026-02-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet_criteria', '0002_alter_criterion7facilities_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('faculty_id', models.IntegerField(db_column='Faculty_ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(db_column='Full_Name', max_length=255)),
                ('academic_rank', models.CharField(db_column='Academic_Rank', max_length=100)),
                ('appointment_type', models.CharField(db_column='Appointment_Type', max_length=100)),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('office_hours', models.TextField(blank=True, db_column='Office_Hours', null=True)),
            ],
            options={
                'db_table': 'FACULTY_MEMBER',
                'managed': False,
            },
        ),
    ]
