# Generated by Django 6.0.2 on 2026-02-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet_criteria', '0004_criterion7facilities_is_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppendixA',
            fields=[
                ('appendixA_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'APPENIXA',
            },
        ),
        migrations.CreateModel(
            name='Criterion5Curriculum',
            fields=[
                ('criterion5_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_calender_type', models.CharField(max_length=50)),
                ('curriculum_alignment_description', models.TextField()),
                ('prerequisites_support_description', models.TextField()),
                ('hours_depth_by_subject_area_description', models.TextField()),
                ('broad_education_component_description', models.TextField()),
                ('cooperative_education_description', models.TextField()),
                ('materials_available_description', models.TextField()),
                ('culminating_design_experience', models.TextField()),
                ('curricular_paths', models.TextField(db_column='Curricular_paths')),
            ],
            options={
                'db_table': 'CRITERION_5_CURRICULUM',
            },
        ),
        migrations.AddField(
            model_name='accreditationcycle',
            name='appendixA',
            field=models.ForeignKey(blank=True, db_column='appendixA_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.appendixa'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='appendixA',
            field=models.ForeignKey(blank=True, db_column='appendixA_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.appendixa'),
        ),
        migrations.CreateModel(
            name='AppendixCEquipment',
            fields=[
                ('appendix_c_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated_date', models.DateField()),
                ('labs_covered_count', models.IntegerField()),
                ('equipment_items_count', models.IntegerField()),
                ('high_value_assets_count', models.IntegerField()),
                ('cycle', models.ForeignKey(db_column='Cycle_ID', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.accreditationcycle')),
            ],
            options={
                'db_table': 'APPENDIX_C_EQUIPMENT',
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='appendix_c',
            field=models.ForeignKey(blank=True, db_column='appendix_c_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.appendixcequipment'),
        ),
        migrations.AddField(
            model_name='accreditationcycle',
            name='criterion5',
            field=models.ForeignKey(blank=True, db_column='criterion5_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion5curriculum'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='criterion5',
            field=models.ForeignKey(blank=True, db_column='criterion5_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion5curriculum'),
        ),
        migrations.CreateModel(
            name='Criterion6Faculty',
            fields=[
                ('criterion6_id', models.AutoField(primary_key=True, serialize=False)),
                ('faculty_composition_narrative', models.TextField()),
                ('faculty_worklaod_expectations_description', models.TextField()),
                ('workload_expectations_desciption', models.TextField()),
                ('faculty_size_adequacy_description', models.TextField()),
                ('advising_and_student_interaction_description', models.TextField()),
                ('service_and_industry_engagement_description', models.TextField()),
                ('course_creation_role_description', models.TextField()),
                ('peo_ro_role_description', models.TextField()),
                ('leadership_roles_description', models.TextField()),
                ('cycle', models.ForeignKey(db_column='Cycle_ID', on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.accreditationcycle')),
            ],
            options={
                'db_table': 'CRITERION_6_FACULTY',
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='criterion6',
            field=models.ForeignKey(blank=True, db_column='criterion6_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abet_criteria.criterion6faculty'),
        ),
    ]
