# Generated by Django 6.0.2 on 2026-02-17 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet_criteria', '0005_criterion1students_appendixa_criterion5curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSupportUnit',
            fields=[
                ('support_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('responsible_person_name', models.CharField(max_length=255)),
                ('responsible_person_title', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ACADEMIC_SUPPORT_UNIT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('additional_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('design_content_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('software_or_labs_tools_used', models.TextField()),
            ],
            options={
                'db_table': 'ADDITIONAL_INFORMATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppendixB',
            fields=[
                ('appendixB_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'APPENDIXB',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppendixDInstitution',
            fields=[
                ('appendix_d_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('institutiton_address', models.TextField()),
                ('chief_executive_name', models.CharField(max_length=255)),
                ('chief_ececutive_title', models.CharField(max_length=255)),
                ('self_study_submitter_name', models.CharField(max_length=255)),
                ('self_study_submitter_title', models.CharField(max_length=255)),
                ('institutional_accreditations', models.TextField()),
                ('accreditation_evalutaion_dates', models.TextField()),
                ('control_type_description', models.TextField()),
                ('administrative_chain_description', models.TextField()),
                ('organization_chart_file_reference', models.TextField()),
                ('credit_hour_definition', models.TextField()),
                ('deviations_from_standard', models.TextField()),
            ],
            options={
                'db_table': 'APPENDIX_D_INSTITUTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assesment_type', models.CharField(max_length=100)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'ASSESMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssignedTo',
            fields=[
                ('program', models.ForeignKey(db_column='program_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abet_criteria.program')),
            ],
            options={
                'db_table': 'ASSIGNED_TO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BackgroundInfo',
            fields=[
                ('background_id', models.AutoField(db_column='background_id_', primary_key=True, serialize=False)),
                ('program_contact_name', models.CharField(max_length=255)),
                ('contact_title', models.CharField(max_length=255)),
                ('office_location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=255)),
                ('year_implemented', models.IntegerField()),
                ('last_general_review_date', models.DateField()),
                ('summary_of_major_changes', models.TextField()),
            ],
            options={
                'db_table': 'BACKGROUND_INFO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('certification_id', models.AutoField(db_column='Certification_ID', primary_key=True, serialize=False)),
                ('certification_title', models.CharField(db_column='Certification_title', max_length=255)),
            ],
            options={
                'db_table': 'CERTIFICATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CiActionRow',
            fields=[
                ('ci_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('trigger_description', models.TextField()),
                ('action_taken', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('reassessment_result', models.TextField()),
            ],
            options={
                'db_table': 'CI_ACTION_ROW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clo',
            fields=[
                ('clo_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CLO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corequisite',
            fields=[
                ('corequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'COREQUISITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(db_column='Course_ID', primary_key=True, serialize=False)),
                ('course_code', models.CharField(db_column='Course_Code', max_length=50)),
                ('credits', models.IntegerField(db_column='Credits')),
                ('contact_hours', models.IntegerField(db_column='Contact_Hours')),
                ('course_type', models.CharField(db_column='Course_Type', max_length=50)),
            ],
            options={
                'db_table': 'COURSE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDiscription',
            fields=[
                ('description_id', models.AutoField(primary_key=True, serialize=False)),
                ('catalog_description', models.TextField()),
            ],
            options={
                'db_table': 'COURSE_DISCRIPTION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterion1Students',
            fields=[
                ('criterion1_id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_requirements', models.TextField(blank=True, default='')),
                ('admission_process_summary', models.TextField(blank=True, default='')),
                ('transfer_pathways', models.TextField(blank=True, default='')),
                ('pperformance_evaluation_process', models.TextField(blank=True, default='')),
                ('prerequisite_verification_method', models.TextField(blank=True, default='')),
                ('prerequisite_not_met_action', models.TextField(blank=True, default='')),
                ('transfer_policy_summary', models.TextField(blank=True, default='')),
                ('transfer_credit_evaluation_process', models.TextField(blank=True, default='')),
                ('articulation_agreements', models.TextField(blank=True, default='')),
                ('advising_providers', models.TextField(blank=True, default='')),
                ('advising_frequency', models.TextField(blank=True, default='')),
                ('career_guidance_description', models.TextField(blank=True, default='')),
                ('work_in_lieu_policies', models.TextField(blank=True, default='')),
                ('work_in_lieu_approval_process', models.TextField(blank=True, default='')),
                ('minimum_required_credits', models.IntegerField(default=0)),
                ('required_gpa_or_standing', models.CharField(blank=True, default='', max_length=50)),
                ('essential_courses_categories', models.TextField(blank=True, default='')),
                ('degree_name', models.CharField(blank=True, default='', max_length=255)),
                ('transcript_format_explanation', models.TextField(blank=True, default='')),
                ('program_name_on_transcript', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'CRITERION_1_STUDENTS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Criterion4',
            fields=[
                ('criterion4_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_processes_description', models.TextField()),
                ('assessment_frequency_description', models.TextField()),
                ('documentation_storage_description', models.TextField()),
                ('ci_process_description', models.TextField()),
                ('recent_changes_description', models.TextField()),
                ('future_improvement_plans_description', models.TextField()),
                ('assessment_instruments_available', models.TextField()),
                ('meeting_minutes_available', models.TextField()),
                ('advisory_board_recommendations_available', models.TextField()),
                ('disaggregated_data_available', models.TextField()),
                ('onsite_review_notes', models.TextField()),
            ],
            options={
                'db_table': 'CRITERION_4',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourseRow',
            fields=[
                ('curr_course_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_se_category', models.CharField(max_length=100)),
                ('math_basic_sciences_credits', models.IntegerField()),
                ('engineering_topics_credits', models.IntegerField()),
                ('other_credits', models.IntegerField()),
                ('last_two_terms_offered', models.CharField(max_length=100)),
                ('max_section_enrollment', models.IntegerField()),
            ],
            options={
                'db_table': 'CURRICULUM_COURSE_ROW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DesignProjectRow',
            fields=[
                ('design_project_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=255)),
                ('team_identifier', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'DESIGN_PROJECT_ROW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('enrollment_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('student_type', models.CharField(max_length=100)),
                ('year1_count', models.IntegerField()),
                ('year2_count', models.IntegerField()),
                ('year3_count', models.IntegerField()),
                ('year4_count', models.IntegerField()),
                ('year5_count', models.IntegerField()),
                ('total_undergraduate', models.IntegerField()),
                ('total_graduate', models.IntegerField()),
                ('associates_awarded', models.IntegerField()),
                ('bachelors_awarded', models.IntegerField()),
                ('masters_awarded', models.IntegerField()),
                ('doctorates_awarded', models.IntegerField()),
            ],
            options={
                'db_table': 'ENROLLMENT_RECORD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('location_lab', models.CharField(max_length=255)),
                ('instructional_use', models.TextField()),
                ('last_service_date', models.DateField()),
                ('evidence_link', models.TextField()),
            ],
            options={
                'db_table': 'EQUIPMENT_ITEM',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyQualificationRow',
            fields=[
                ('faculty_qualification_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('highest_degree_field', models.CharField(max_length=255)),
                ('highest_degree_year', models.IntegerField()),
                ('academic_rank', models.CharField(max_length=100)),
                ('academic_appointment', models.CharField(max_length=100)),
                ('full_time_or_part_time', models.CharField(max_length=50)),
                ('years_gov_industry', models.IntegerField()),
                ('years_teaching', models.IntegerField()),
                ('years_at_institution', models.IntegerField()),
                ('professional_registration', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'FACULTY_QUALIFICATION_ROW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacultyWorkloadRow',
            fields=[
                ('faculty_workload_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('fill_tie_or_part_time', models.CharField(max_length=50)),
                ('classes_taught_description', models.TextField()),
                ('term', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'db_table': 'FACULTY_WORKLOAD_ROW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HonorAward',
            fields=[
                ('award_id', models.AutoField(db_column='Award_ID', primary_key=True, serialize=False)),
                ('award_discription', models.TextField(db_column='Award_discription')),
            ],
            options={
                'db_table': 'HONOR_AWARD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndustryExperience',
            fields=[
                ('experience_id', models.AutoField(db_column='Experience_ID', primary_key=True, serialize=False)),
                ('experience_discription', models.TextField(db_column='Experience_discription')),
            ],
            options={
                'db_table': 'INDUSTRY_EXPERIENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorSyllabus',
            fields=[
                ('syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=50)),
                ('syllabus_status', models.IntegerField()),
            ],
            options={
                'db_table': 'INSTRUCTOR_SYLLABUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentOutcome',
            fields=[
                ('so_id', models.AutoField(primary_key=True, serialize=False)),
                ('so_code', models.CharField(max_length=20, unique=True)),
                ('so_discription', models.TextField()),
            ],
            options={
                'db_table': 'STUDENT_OUTCOME',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NonacademicSupportUnit',
            fields=[
                ('nonacademic_support_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('responsible_person_name', models.CharField(max_length=255)),
                ('responsible_person_title', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'NONACADEMIC_SUPPORT_UNIT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutcomeAttainmentRow',
            fields=[
                ('attainment_row_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_evidence', models.TextField()),
                ('target_attainment', models.CharField(max_length=100)),
                ('evaluation_summary', models.TextField()),
                ('where_stored', models.TextField()),
            ],
            options={
                'db_table': 'OUTCOME_ATTAINMENT_ROW',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Peo',
            fields=[
                ('peo_id', models.AutoField(primary_key=True, serialize=False)),
                ('peo_code', models.CharField(max_length=20, unique=True)),
                ('peo_description', models.TextField()),
            ],
            options={
                'db_table': 'PEO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonnelRecord',
            fields=[
                ('personnel_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('employment_category', models.CharField(max_length=150)),
                ('full_time_count', models.IntegerField()),
                ('part_time_count', models.IntegerField()),
                ('fte_count', models.IntegerField()),
            ],
            options={
                'db_table': 'PERSONNEL_RECORD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('prerequisite_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PREREQUISITE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDevelopment',
            fields=[
                ('development_id', models.AutoField(db_column='Development_ID', primary_key=True, serialize=False)),
                ('activity_description', models.TextField(db_column='Activity_Description')),
            ],
            options={
                'db_table': 'PROFESSIONAL_DEVELOPMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalMembership',
            fields=[
                ('membership_id', models.AutoField(db_column='Membership_ID', primary_key=True, serialize=False)),
                ('membership_description', models.TextField(db_column='Membership_Description')),
            ],
            options={
                'db_table': 'PROFESSIONAL_MEMBERSHIP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.AutoField(db_column='Publication_ID', primary_key=True, serialize=False)),
                ('publication_discription', models.TextField(db_column='Publication_Discription')),
            ],
            options={
                'db_table': 'PUBLICATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('qualification_id', models.AutoField(db_column='Qualification_ID', primary_key=True, serialize=False)),
                ('degree_field', models.CharField(db_column='Degree_Field', max_length=255)),
                ('degree_institution', models.CharField(db_column='Degree_Institution', max_length=255)),
                ('degree_year', models.IntegerField(db_column='Degree_Year')),
                ('years_industry_government', models.IntegerField(db_column='Years_Industry_Government')),
                ('years_at_institution', models.IntegerField(db_column='Years_At_Institution')),
            ],
            options={
                'db_table': 'QUALIFICATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsibleFor',
            fields=[
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abet_criteria.user')),
            ],
            options={
                'db_table': 'RESPONSIBLE_FOR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('service_id', models.AutoField(db_column='Service_ID', primary_key=True, serialize=False)),
                ('service_description', models.TextField(db_column='Service_Description')),
            ],
            options={
                'db_table': 'SERVICE_ACTIVITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplementMaterial',
            fields=[
                ('material_id', models.AutoField(primary_key=True, serialize=False)),
                ('material_discription', models.TextField()),
            ],
            options={
                'db_table': 'SUPPLEMENT_MATERIAL',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('faculty', models.ForeignKey(db_column='Faculty_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abet_criteria.facultymember')),
            ],
            options={
                'db_table': 'TEACHES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('textbook_id', models.AutoField(primary_key=True, serialize=False)),
                ('title_author_year', models.TextField()),
                ('attribute', models.TextField(db_column='Attribute')),
            ],
            options={
                'db_table': 'TEXTBOOK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedSyllabus',
            fields=[
                ('unified_syllabus_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'UNIFIED_SYLLABUS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeeklyTopicOutline',
            fields=[
                ('outline_id', models.AutoField(primary_key=True, serialize=False)),
                ('topics_description', models.TextField()),
            ],
            options={
                'db_table': 'WEEKLY_TOPIC_OUTLINE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('workload_id', models.AutoField(db_column='Workload_ID', primary_key=True, serialize=False)),
                ('teaching_percentage', models.DecimalField(db_column='Teaching_Percentage', decimal_places=2, max_digits=5)),
                ('research_percentage', models.DecimalField(db_column='Research_Percentage', decimal_places=2, max_digits=5)),
                ('other_percentage', models.DecimalField(db_column='Other_Percentage', decimal_places=2, max_digits=5)),
                ('program_time_percentage', models.DecimalField(db_column='Program_Time_Percentage', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'WORKLOAD',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HasClo',
            fields=[
                ('clo', models.ForeignKey(db_column='clo_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abet_criteria.clo')),
            ],
            options={
                'db_table': 'HAS_CLO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapsTo',
            fields=[
                ('so', models.ForeignKey(db_column='so_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abet_criteria.studentoutcome')),
            ],
            options={
                'db_table': 'MAPS_TO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupportsPeo',
            fields=[
                ('so', models.ForeignKey(db_column='so_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abet_criteria.studentoutcome')),
            ],
            options={
                'db_table': 'SUPPORTS_PEO',
                'managed': False,
            },
        ),
    ]
