# Generated by Django 6.0.2 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abet_criteria', '0006_academicsupportunit_additionalinformation_appendixb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterion5curriculum',
            name='design_project_rows',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='criterion5curriculum',
            name='plan_of_study_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='criterion5curriculum',
            name='prerequisite_flowchart_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='criterion5curriculum',
            name='table_5_1_rows',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
